### PR TITLE
Add handler for broken GitHub connection

### PR DESCRIPTION
**Pull request by JesusLeon**
Hey, here's my try. Hopefully it passes :)

Handles issue #17

### CODE REVIEW

**Comment by jwalton512** [comment]
I think one potential issue with this solution is that it makes the assumption that every Github exception is a 401 Unauthorized.  I think there should be a conditional that checks the client to see exactly what the last response status code was.

**Comment by JesusLeon** [comment]
@jwalton512 true, what about this: ab66c03a09731053e72f531a37d3cd34bf7f420f

**Comment by JesusLeon** [comment]
I've switched to get the code from the `$client` instance instead of the exception `$e` one.

**Comment by mattstauffer** [comment]
Thanks @JesusLeon! I'm gonna pull this and do some updates and then merge it--appreciate your work here!

**Comment by mattstauffer** [comment]
And thanks @jwalton512 for the review!

**Pull request merged**
