### PR TITLE
Laravel 5.2 Shift

### PR DESCRIPTION
**Pull request by mattstauffer**
This pull request includes the changes for upgrading to Laravel 5.2. Feel free to commit any additional changes to the `shift-16540` branch.

**Before merging**, you should:

- Checkout the `shift-16540` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 5.2
- Run `composer update` (if the pre-scripts fail, add `--no-scripts`)
- Thoroughly test your application

If you want help with your upgrade, check out the [Shift Human Services](https://laravelshift.com/human-services) or join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack room to get answers to all your Laravel questions.

### CODE REVIEW

**Comment by mattstauffer** [comment]
:x: Laravel 5.2 modified the default Middleware. Since your middleware differs from the Laravel 5.1 default, you will need to compare the following middleware against the [5.2 versions](https://github.com/laravel-shift/laravel-5.2/tree/master/app/Http/Middleware) and merge any changes.

- [ ] app/Http/Middleware/Authenticate.php
- [ ] app/Http/Middleware/EncryptCookies.php
- [ ] app/Http/Middleware/RedirectIfAuthenticated.php

**Comment by mattstauffer** [comment]
:x: Laravel 5.2 separates _web_ and _API_ functionality with [Middleware Groups](http://laravel.com/docs/5.2/middleware#middleware-groups). Shift was unable to completely automate these changes. You will need to compare the following files against the [5.2 versions](https://github.com/laravel-shift/laravel-5.2/) and merge any changes.

- [ ] app/Http/Kernel.php
- [ ] app/Providers/RouteServiceProvider.php

**Comment by mattstauffer** [comment]
:x: The Authentication configuration changed significantly in Laravel 5.2. Since your `config/auth.php` differs from the Laravel 5.1 default, you will need to compare yours against the [5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/config/auth.php) and merge any changes.

**Comment by mattstauffer** [comment]
:information_source: Laravel 5.2 changed the value of `$redirectTo` from `/home` to `/` in `app/Http/Controllers/Auth/AuthController.php`. Shift did not make this change since you may have customized it for your app. However, you may wish to change this if you are not using *Auth* or if you want to follow the latest Laravel conventions.

**Comment by mattstauffer** [comment]
:x: Laravel 5.2 condenses the default User model dramatically. Since your `app/User.php` differs from the Laravel 5.1 default, you will need to compare yours against the [5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/app/User.php) and merge any changes.

**Comment by mattstauffer** [comment]
:warning: `pluck`, `keys`, `zip`, `collapse`, `flatten`, `flip` now return a collection in Laravel 5.2. You should review your usage of these methods.

Shift found potential uses of these methods in:

- [ ] app/Jobs/NotifyUserOfNewGistComments.php

**Comment by mattstauffer** [comment]
:information_source: Laravel 5.2 updated the `database` session driver. If you are using the `database` driver, you will need to add the `user_id` (nullable integer), `ip_address` (nullable string), and `user_agent` (text) columns to your session database table.

**Comment by mattstauffer** [comment]
:warning: Shift was unable to upgrade `phpunit.xml` since yours differed from the Laravel default. You will need to compare your `phpunit.xml` with the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/phpunit.xml) and merge any changes.

**Comment by mattstauffer** [comment]
:x: Laravel 5.2 updated the `public/.htaccess` to handle the *Authorization* header. Since your `public/.htaccess` file differed from the Laravel default, you will need to review the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/public/.htaccess) and merge any changes.

**Comment by mattstauffer** [comment]
:x: Laravel 5.2 updated some of the default validation messages. Since your `resources/lang/en/validation.php` differed from the Laravel default, you will need to review the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/resources/lang/en/validation.php) and merge any changes.

**Comment by mattstauffer** [comment]
:x: Shift could not upgrade the following configuration files since they differed from the default Laravel version. You will need to compare these configuration files against the [default Laravel 5.2 configuration files](https://github.com/laravel-shift/laravel-5.2/tree/master/config) and merge any changes:

- [ ] config/auth.php
- [ ] config/broadcasting.php
- [ ] config/cache.php
- [ ] config/compile.php
- [ ] config/database.php
- [ ] config/filesystems.php
- [ ] config/mail.php
- [ ] config/queue.php
- [ ] config/services.php
- [ ] config/session.php
- [ ] config/view.php

**Comment by mattstauffer** [comment]
:warning: Laravel 5.2 upgraded some of the Node package dependencies. You should to compare your `package.json` with the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/package.json) to upgrade your dependencies.

**Comment by mattstauffer** [comment]
:warning: Laravel 5.2 upgraded its dependency of the `vlucas/phpdotenv` package from `~1.0` to `~2.2`. This version now requires any values containing spaces to be quoted. For example, previously `APP_NAME=Laravel Shift` should now be `APP_NAME="Laravel Shift"`.
You should review your `.env` file to ensure any values containing spaces are properly quoted.

**Comment by bakerkretzmar** [comment]
Closing because we updated to 5.8 in #65.

**Pull request closed without merging**
